In [10]:
import numpy as np
a=np.array([1,2,5,3])
print("Adding 1 :",a+1)
print("sub 3:",a-3)
print("multiply by 10:",a*10)
print("squaring each element:",a**2)
print("Doubled element of array:",a*2)
a=np.array([[1,2,3],[3,4,5],[9,6,0]])
print("/n original array:",a)
print("transpose array:",a.T)

Adding 1 : [2 3 6 4]
sub 3: [-2 -1  2  0]
multiply by 10: [10 20 50 30]
squaring each element: [ 1  4 25  9]
Doubled element of array: [ 2  4 10  6]
/n original array: [[1 2 3]
 [3 4 5]
 [9 6 0]]
transpose array: [[1 3 9]
 [2 4 6]
 [3 5 0]]
