In [1]:
import numpy as np
array_data=np.arange(0,16).reshape((4,4))
print("original array:")
print(array_data)
print("\n Extracted data :third and fourth elements of the first and second rows")
print(array_data[0:2,2:4])

original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 Extracted data :third and fourth elements of the first and second rows
[[2 3]
 [6 7]]
